spring:
    h2:
        console:
            enabled: true
            path: /console
            settings: 
                web-allow-others: true
    datasource:
        url: jdbc:h2:~/test;
        username: sa
        password:
        driverClassName: org.h2.Driver
    # 아래 jpa부분은 참고입니다. h2와 datasource부분만 적용시켜주시면 됩니다.
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                hibernate: 
                    dialect: org.hibernate.dialect.H2Dialect
        database-platform: org.hibernate.dialect.H2Dialect

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: strict